language: node_js
node_js:
  - '8'
  - 'node'
install:
  - npm install
script:
  - npm run lint
  - npm test
after_script:
  - npx nyc report --reporter=text-lcov | npx coveralls
notifications:
  email: false
